### ISSUE TITLE
focus is not called with Rails 5

### ISSUE THREAD

**Issue by rhymes** [seattlerb/minitest-focus#12]
it's just plainly ignored, either by using "rake test" or the new "rails test" shortcut.

I have minitest-focus in my test group and use it as usual.

**Comment by zenspider** [comment]
I don't think that's minitest-focus' fault. rails5 changed a LOT of stuff having to do with the runner. If it worked in rails4 and doesn't on rails5, please look there first.

**Comment by rhymes** [comment]
@zenspider didn't want to assign blame, just make you aware of this :)

**Comment by zenspider** [comment]
Sure, I understand that... Just pointing out that if you want a solution, you probably need to file a bug on the rails project.

**Comment by zenspider** [comment]
Have you filed a bug with rails? Can you link to it here?

**Comment by rhymes** [comment]
@zenspider no sorry, I didn't have the time. In addition I'm not familiar with either code so I wouldn't know what to write in the issue...

**Comment by zenspider** [comment]
Same thing you wrote in mine. Your responsibility is to communicate, not solve. Let the devs figure it out.

**Comment by zenspider** [comment]
No communication from OP. Closing.

**Comment by zenspider** [comment]
@tenderlove heads up^^^ Maybe you can translate this to a rails ticket?

**Comment by mrteera** [comment]
Similar issue here with some more detail: https://github.com/blowmage/minitest-rails/issues/185#issuecomment-192267190

**Comment by jdborneman** [comment]
Did anyone ever resolve this? 
I have:
minitest 5.10.2
minitest-focus 1.1.2
minitest-ar-assertions 0.1.1
minitest-reporters 1.1.14

also later added 
minitest-rails 3.0.0

I'm experiencing the issue where when I put focus on a test, nothing happens at all. focus is completely ignored and all tests run.

my test-helper requires:
require "rails/test_help"
require "mocha/mini_test"
require "minitest"
require "minitest/spec"
require "minitest/mock"
require "minitest/focus"
require "minitest/autorun"

(some of those may not be necessary but have tried adding a lot to resolve this issue to no effect)

ANy ideas on where I can look into this or if it's been solved somehow and my google search-fu is just weak?

Thanks!

**Comment by zenspider** [comment]
@jdborneman it's a problem with rails but it seems that @arthurnn thinks it is fixed? Please file an issue on rails and link back here.

**Comment by jdborneman** [comment]
Done. Thanks!
https://github.com/rails/rails/issues/29469

**Comment by jdborneman** [comment]
They closed my ticket on the rails side without comment. :\

**Comment by zenspider** [comment]
No they didn't.

**Comment by jdborneman** [comment]
I misread. Saw the link to here as closed and misread. Oops
