### ISSUE TITLE
`focus` method causes backports/tools.rb to crash

### ISSUE THREAD

**Issue by davesag** [seattlerb/minitest-focus#4]
In my `Sinatra` app I am trying to use minitest-focus 1.1.0 (thanks for the minutest v5 fix) my test, written using minitest/spec as follows (trimmed for example)

    require 'minitest_helper'

    describe MyController do
      include Rack::Test::Methods
      include FactoryGirl::Syntax::Methods
      include Warden::Test::Helpers

      def app
        MyApplication
      end

      let(:user) { create(:a_user) }
      let(:game) { create(:a_game) }

      before do
        DatabaseCleaner.start
      end

      after do
        DatabaseCleaner.clean
      end

      describe 'game play' do
        
        focus
        it "should launch a game if a user is logged in" do
          user.wont_be_nil
          login_as user
          get "/games/play/#{game.id}"
          last_response.must_be :ok?
        end
        
      end

    end

I'm using `Warden::Test::Helpers`, `SimpleCov`, `FactoryGirl`, `DatabaseCleaner` and the `Rack::Test::Methods`.

Tests are run via `RACK_ENV=test bundle exec rake` and results in

    /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/backports-3.3.4/lib/backports/tools.rb:328:in `require': cannot load such file -- /^(MyApplication::MyController::game play#test_0003_should launch a game if a user is logged in)$ (LoadError)
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/backports-3.3.4/lib/backports/tools.rb:328:in `require_with_backports'
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in require'
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.0/lib/rake/rake_test_loader.rb:4:in `select'
    	from /Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.0/lib/rake/rake_test_loader.rb:4:in `<main>'
    rake aborted!
    Command failed with status (1): [ruby -I"lib:spec" -I"/Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.0/lib" "/Users/davesag/.rvm/gems/ruby-2.0.0-p247/gems/rake-10.1.0/lib/rake/rake_test_loader.rb" "spec/**/*_spec.rb" ]

If I comment out the `focus` method this test runs fine along with all the others.

**Comment by zenspider** [comment]
I'm tempted to close this...
